### PR TITLE
Added share feature

### LINKED ISSUE #5: Share button
It would be great to see a share button on the bottom right of the cards:

image

image

so that one can click on it and get a prompt to share an image of the card view to social media platforms. It would be nice to see a small text "Shared from QuotesApp made by Gourav."

Here's an example:

Add a subheading

This is just a sample, fonts and color scheme isn't shown. This is just a gist of what I think would make the app super awesome :)

### PR DESCRIPTION
**Pull request by xtanion**
fixes #5 

Added share quote feature with UI same as mentioned in issue#5. Here's the sample screenshot 😃

### CODE REVIEW

**Comment by xtanion** [comment]
hey @gouravkhunger please take a look at my PR, I can share a screencast demo if you want, Thanks.

**Comment by xtanion** [comment]
Sure, It won't be tough and I'll add screencast as well 😃

**Comment by gouravkhunger** [comment]
Also, remove the `Made by...` line. It's an open source project, we should add a line thanks to the contributors, but since it is an image we can't link to the GitHub, I will add credits to the app in some section in a while.

For now, just keep it "Shared from Quotes App by Gourav Khunger" instead of a new line.

**Comment by gouravkhunger** [comment]
That's great progress!
Here are the final changes that would make it next level :)

- Name is "Gourav"(o instead of a) 😆 
- It would be better if you wrap the author text view and the share image view in a Relative Layout so that they can be in the same line, while the author card being on the leftmost side and the share button on the rightmost side :)
- Let's make the generated image a square, rather than a rectangle. Right now, it is still leaving space on the top and bottom removing which will make it look better. For example, this is what would look better than a rectangular image.

image

**Comment by xtanion** [comment]
Do you want the text to appear like this -
```
the primary cause of unhappiness is never the situation but your thoughts about it - Eckhart Tolle
```
or like this -
```
the primary cause of unhappiness is never the situation but your thoughts about it 
- Eckhart Tolle
```

**Comment by gouravkhunger** [comment]
Amazing! Forgot to remind you to wrap the author text view and image text view in a relative layout as in here(open the file to look around):

https://github.com/gouravkhunger/QuotesApp/blob/f9ba86bf635047685f03b20e2f5cd48632422405/app/src/main/res/layout/fragment_quote.xml#L79

This will make the share button and text view in a single line rather than this
image

And it will also remove this extra spacing automatically
image

**Comment by xtanion** [comment]
@gouravkhunger Changed some UI elements have a look

<div align="center">
  <p float="left">
    
    
 </p>
</div>

**Pull request merged**
